# Generated by Django 5.0 on 2025-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
        migrations.AddField(
            model_name="account",
            name="checking_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Checking Balance",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="savings_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Saving Balance",
            ),
        ),
    ]
