# Generated by Django 5.0 on 2025-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_account_account_type_remove_account_balance_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="account_number",
            new_name="checking_acc_number",
        ),
        migrations.AddField(
            model_name="account",
            name="savings_acc_number",
            field=models.CharField(default="", max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
