# Generated by Django 5.0 on 2025-08-25 17:16

import cloudinary.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("transfer_internal", "Transfer (Internal)"),
                            ("transfer_external", "Transfer (External Wire)"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("wire_transfer", "Wire Transfer"),
                            ("bank_transfer", "Bank Transfer"),
                            ("internal", "Internal"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Savings"), ("checking", "Checking")],
                        max_length=30,
                        null=True,
                        verbose_name="Transaction Account Type",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("successful", "Successful"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tx_destination",
                        to="accounts.account",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_txs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tx_source",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "beneficiary_account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "beneficiary_bank_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "banking_routing_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_swift_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recipient_address", models.TextField(blank=True, null=True)),
                (
                    "payment_proof",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="payment_proofs",
                    ),
                ),
                (
                    "receipt",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="receipts"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Details",
                "verbose_name_plural": "Transaction Details",
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference"], name="transaction_referen_923a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "status"], name="transaction_categor_a414d5_idx"
            ),
        ),
    ]
