# Generated by Django 5.0 on 2025-08-25 20:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionmeta",
            name="receipt",
        ),
        migrations.AddField(
            model_name="transactionmeta",
            name="payment_proof_2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="payment_proof_2"
            ),
        ),
    ]
