# Generated by Django 5.0 on 2025-08-14 01:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionmeta",
            name="payment_proof",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="payment_proofs"
            ),
        ),
        migrations.AlterField(
            model_name="transactionmeta",
            name="receipt",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="receipts"
            ),
        ),
    ]
