# Generated by Django 5.0 on 2025-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transactionmeta_payment_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
