# Generated by Django 5.0 on 2025-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transactionmeta_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionmeta",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
