# Generated by Django 5.0 on 2025-08-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transactionmeta_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionmeta",
            options={
                "verbose_name": "Transaction Details",
                "verbose_name_plural": "Transaction Details",
            },
        ),
    ]
