# Generated by Django 5.0 on 2025-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
