# Generated by Django 5.0 on 2025-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transactionmeta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="over_ride_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
