# Generated by Django 5.0 on 2025-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
