# Generated by Django 5.0 on 2025-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("savings", "Savings"), ("checking", "Checking")],
                max_length=30,
                null=True,
            ),
        ),
    ]
