# Generated by Django 5.0 on 2025-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_transaction_account_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionmeta",
            name="blockchain_tx_hash",
        ),
        migrations.RemoveField(
            model_name="transactionmeta",
            name="wallet_address",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("wire_transfer", "Wire Transfer"),
                    ("bank_transfer", "Bank Transfer"),
                    ("internal", "Internal"),
                ],
                max_length=24,
            ),
        ),
    ]
