# Generated by Django 5.0 on 2025-09-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="over_ride_created_at",
        ),
    ]
