# Generated by Django 5.0 on 2025-08-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_remove_transactionmeta_blockchain_tx_hash_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="description",
            new_name="error_message",
        ),
    ]
