# Generated by Django 5.0 on 2025-08-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_rename_description_transaction_error_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
            },
        ),
        migrations.AddField(
            model_name="transactionmeta",
            name="bank_swift_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactionmeta",
            name="banking_routing_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transactionmeta",
            name="recipient_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("savings", "Savings"), ("checking", "Checking")],
                max_length=30,
                null=True,
                verbose_name="Transaction Account Type",
            ),
        ),
    ]
