# Generated by Django 5.0 on 2025-08-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionmeta",
            options={
                "verbose_name": "Transaction Details",
                "verbose_name_plural": "Transaction Details",
            },
        ),
    ]
