# Generated by Django 5.0 on 2025-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_tokenvalidator_user_country_user_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenvalidator",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
