# Generated by Django 5.0 on 2025-08-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_tokenvalidator_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenvalidator",
            name="is_active",
        ),
    ]
