# Generated by Django 5.0 on 2025-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_tokenvalidator_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenvalidator",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
