# Generated by Django 5.0 on 2025-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_email_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
