# Generated by Django 5.0 on 2025-08-13 19:57

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ssn', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking')], max_length=25)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('income_range', models.CharField(max_length=35)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('kin_name', models.CharField(max_length=255)),
                ('kin_address', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('kin_date_of_birth', models.DateField()),
                ('document_type', models.CharField(choices=[('passport', 'Int. Passport'), ('national_id', 'National Id'), ('driver_license', 'Driver license')], max_length=50)),
                ('doument_front', models.CharField(max_length=255)),
                ('domument_back', models.CharField(max_length=255)),
                ('passport_image', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Kyc approval status message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
