# Generated by Django 5.0 on 2025-08-14 02:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kyc",
            name="domument_back",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="doument_front",
        ),
        migrations.AddField(
            model_name="kyc",
            name="document_back",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="document_back"
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="document_front",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="document_front"
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="KYC approval status message"
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="kin_date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="passport_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="passport_image"
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
