# Generated by Django 5.0 on 2025-09-05 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_remove_kyc_domument_back_remove_kyc_doument_front_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
