# Generated by Django 5.0 on 2025-09-25 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fcmdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='fcmdevice',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_user_token'),
        ),
    ]
