# Generated by Django 5.0 on 2025-09-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_chat_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
